# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# homebrew basics
tap homebrew/dupes
tap homebrew/versions
install homebrew/dupes/grep

# useful utilities
install grc
install coreutils
install spark
install wget

# Install other useful binaries
install ack
install git
install git-flow 
install node
install tree
install vim --override-system-vi
install dnsmasq
install mysql 
install rbenv 
install rbenv-gem-rehash

# install PHP 5.5 and composer
tap homebrew/homebrew-php
install php55
# install php55-intl
install php55-crypto
install homebrew/php/composer

# install hhvm 
# tap mcuadros/homebrew-hhvm
# install hhvm

# install go
# install go

# brew cask
tap caskroom/cask
install brew-cask
cask install google-chrome firefox opera opera-next aurora alfred iterm2 evernote slack harvest onepassword vagrant dropbox spectacle sequel-pro
cask alfred link
